schema: spec-driven
<<<<<<<< HEAD:openspec/notplan-changes/c999-yaml-dsl-lsp/.openspec.yaml
created: 2026-03-19
========
created: 2026-03-25
>>>>>>>> 7882a67 (Squash commits from issue-run-override-outputs):openspec/notplan-changes/c22-yaml-dsl-cli-effective-yaml-render/.openspec.yaml
