# 本文件由 `scripts/gen-project-constants.py` 自动生成,请勿手改.
# 数据来源: `pyproject.toml` 的 `([project] + [tool.scalim.*])`.

CLI_NAME = "scalim-cli"
DIST_NAME = "scalim"
ENV_BENCH_MAX_WORKERS = "SCALIM_BENCH_MAX_WORKERS"
ENV_BENCH_SCALE = "SCALIM_BENCH_SCALE"
ENV_BENCH_SCOPE = "SCALIM_BENCH_SCOPE"
ENV_EXP_CALL_BY_MEMOIZE_ALLOW = "SCALIM_EXP_CALL_BY_MEMOIZE_ALLOW"
ENV_EXP_CALL_BY_MEMOIZE_DENY = "SCALIM_EXP_CALL_BY_MEMOIZE_DENY"
ENV_EXP_CALL_BY_MEMOIZE_LOG_STATS = "SCALIM_EXP_CALL_BY_MEMOIZE_LOG_STATS"
ENV_EXP_CALL_BY_MEMOIZE_MAX_ENTRIES = "SCALIM_EXP_CALL_BY_MEMOIZE_MAX_ENTRIES"
ENV_PROBE_CALL_BY_DEP_CARDINALITY = "SCALIM_PROBE_CALL_BY_DEP_CARDINALITY"
ENV_SYNC_ANALYSIS_SCRIPT = "SCALIM_ANALYSIS_SCRIPT"
ENV_SYNC_ANALYZE_ARGS = "SCALIM_ANALYZE_ARGS"
ENV_SYNC_ANALYZE_ARGS_PREFIX = "SCALIM_ANALYZE_ARGS_"
ENV_SYNC_DEST_DIR = "SCALIM_DEST_DIR"
ENV_SYNC_LOG_DEST_DIR = "SCALIM_LOG_DEST_DIR"
ENV_SYNC_LOG_REMOTE_DIR = "SCALIM_LOG_REMOTE_DIR"
ENV_SYNC_REMOTE_HOST = "SCALIM_REMOTE_HOST"
ENV_SYNC_REPORT_ROOT_DIR = "SCALIM_REPORT_ROOT_DIR"
ENV_SYNC_TMP_REMOTE_DIR = "SCALIM_TMP_REMOTE_DIR"
IMPORT_ROOT = "scalim"
VERSION = "0.9.23"
VIZ_ARTIFACTS_ROOT = "artifacts/scalim-viz"
VIZ_DIR_NAME = "scalim-viz"
VIZ_REPLAY_ROUTE = "/__scalim_viz__/replay"

__all__ = ()
