"""事件类型、`envelope` 与类型化 `payload` 公共契约.

对外推荐从包根导入,例如:
- `from scalim.events import Event, EventType, PipelineStartEvent, get_event_catalog`

进程内事件身份以 `EventType` 为唯一来源;类型化 `payload` 数据类为公开契约.
以下划线开头的实现模块不是用户导入契约.
"""

# pragma: scalim-public-api tier1:110:scalim.events|事件envelope+EventType+公开payload+事件目录|写 Observer/Hook;按 EventType 订阅/过滤
# pragma: scalim-public-api tier1:111:scalim.events.type_groups|事件类型分组视图|按主题探索 EventType(不引入新值)

from ._events import (
    AdaptiveSchedulerDecisionEvent,
    BatchEndEvent,
    BatchStartEvent,
    ColumnWriteEvent,
    DiagnosticWarningEvent,
    ErrorEvent,
    FieldComputeEvent,
    FieldSlimEvent,
    LoaderCallEvent,
    LoaderRetryEvent,
    LoaderSlimEvent,
    OperatorSpanEvent,
    OutputTargetEndEvent,
    PipelineEndEvent,
    PipelineStartEvent,
    RelationLookupEvent,
    RowReleaseEvent,
    RowWriteEvent,
    StageSpanEvent,
    WorkflowCacheAcquireEvent,
    WorkflowCacheEvictEvent,
    WorkflowCacheReleaseEvent,
    WorkflowFinishedEvent,
    WorkflowNodeCancelledEvent,
    WorkflowNodeEndEvent,
    WorkflowNodeStartEvent,
    WorkflowResourceCommitEvent,
    WorkflowResourceCreateEvent,
    WorkflowResourceDiscardEvent,
    WorkflowResourceWriteEvent,
    WorkflowStartedEvent,
)
from .api import (
    WORKFLOW_ATTRIBUTION_META_KEYS,
    WORKFLOW_EXEC_ID_META_KEY,
    WORKFLOW_NODE_ID_META_KEY,
    Event,
    EventDescriptor,
    EventType,
    WorkflowNodeCancelledReason,
    WorkflowNodeEndStatus,
    generate_run_id,
    get_event_catalog,
    get_event_catalog_map,
    now_ts,
    parse_event_type,
)

__all__ = (
    "WORKFLOW_ATTRIBUTION_META_KEYS",
    "WORKFLOW_EXEC_ID_META_KEY",
    "WORKFLOW_NODE_ID_META_KEY",
    "AdaptiveSchedulerDecisionEvent",
    "BatchEndEvent",
    "BatchStartEvent",
    "ColumnWriteEvent",
    "DiagnosticWarningEvent",
    "ErrorEvent",
    "Event",
    "EventDescriptor",
    "EventType",
    "FieldComputeEvent",
    "FieldSlimEvent",
    "LoaderCallEvent",
    "LoaderRetryEvent",
    "LoaderSlimEvent",
    "OperatorSpanEvent",
    "OutputTargetEndEvent",
    "PipelineEndEvent",
    "PipelineStartEvent",
    "RelationLookupEvent",
    "RowReleaseEvent",
    "RowWriteEvent",
    "StageSpanEvent",
    "WorkflowCacheAcquireEvent",
    "WorkflowCacheEvictEvent",
    "WorkflowCacheReleaseEvent",
    "WorkflowFinishedEvent",
    "WorkflowNodeCancelledEvent",
    "WorkflowNodeCancelledReason",
    "WorkflowNodeEndEvent",
    "WorkflowNodeEndStatus",
    "WorkflowNodeStartEvent",
    "WorkflowResourceCommitEvent",
    "WorkflowResourceCreateEvent",
    "WorkflowResourceDiscardEvent",
    "WorkflowResourceWriteEvent",
    "WorkflowStartedEvent",
    "generate_run_id",
    "get_event_catalog",
    "get_event_catalog_map",
    "now_ts",
    "parse_event_type",
)
