"""`events` 对外稳定导出面.

说明:
- 对外稳定导入路径为 `scalim.events`.
- 事件 `event_type` 的值域仍为稳定字符串;本模块提供结构化的枚举访问,便于订阅/过滤.
- 具体实现细节分散在 `_*.py` 内部模块中(非公共契约).
"""

from enum import Enum

from ..vendor.compact.typing_extensionsx import override
from ._attribution import WORKFLOW_ATTRIBUTION_META_KEYS, WORKFLOW_EXEC_ID_META_KEY, WORKFLOW_NODE_ID_META_KEY
from ._catalog import (
    EVENT_ADAPTIVE_SCHEDULER_DECISION,
    EVENT_BATCH_END,
    EVENT_BATCH_START,
    EVENT_COLUMN_WRITE,
    EVENT_DIAGNOSTIC_WARNING,
    EVENT_ERROR,
    EVENT_FIELD_COMPUTE,
    EVENT_FIELD_SLIM,
    EVENT_LOADER_CALL,
    EVENT_LOADER_RETRY,
    EVENT_LOADER_SLIM,
    EVENT_OPERATOR_SPAN,
    EVENT_OUTPUT_TARGET_END,
    EVENT_PIPELINE_END,
    EVENT_PIPELINE_START,
    EVENT_PRE_USE_BATCH_SIZE,
    EVENT_RELATION_LOOKUP,
    EVENT_ROW_RELEASE,
    EVENT_ROW_WRITE,
    EVENT_STAGE_SPAN,
    EVENT_WORKFLOW_CACHE_ACQUIRE,
    EVENT_WORKFLOW_CACHE_EVICT,
    EVENT_WORKFLOW_CACHE_RELEASE,
    EVENT_WORKFLOW_FINISHED,
    EVENT_WORKFLOW_NODE_CANCELLED,
    EVENT_WORKFLOW_NODE_END,
    EVENT_WORKFLOW_NODE_START,
    EVENT_WORKFLOW_RESOURCE_COMMIT,
    EVENT_WORKFLOW_RESOURCE_CREATE,
    EVENT_WORKFLOW_RESOURCE_DISCARD,
    EVENT_WORKFLOW_RESOURCE_WRITE,
    EVENT_WORKFLOW_STARTED,
    WORKFLOW_NODE_CANCELLED_REASON_DEPENDENCY_FAILED,
    WORKFLOW_NODE_CANCELLED_REASON_POLICY_ALL_FAIL,
    WORKFLOW_NODE_CANCELLED_REASON_UPSTREAM_CANCELLED,
    WORKFLOW_NODE_END_STATUS_ERROR,
    WORKFLOW_NODE_END_STATUS_OK,
    EventDescriptor,
    get_event_catalog,
    get_event_catalog_map,
)
from ._event import Event, generate_run_id, now_ts


class EventType(str, Enum):
    """稳定事件类型枚举(值域为稳定字符串)."""

    PIPELINE_START = EVENT_PIPELINE_START
    PIPELINE_END = EVENT_PIPELINE_END
    BATCH_START = EVENT_BATCH_START
    BATCH_END = EVENT_BATCH_END
    LOADER_CALL = EVENT_LOADER_CALL
    LOADER_RETRY = EVENT_LOADER_RETRY
    FIELD_COMPUTE = EVENT_FIELD_COMPUTE
    ERROR = EVENT_ERROR
    DIAGNOSTIC_WARNING = EVENT_DIAGNOSTIC_WARNING
    FIELD_SLIM = EVENT_FIELD_SLIM
    ROW_WRITE = EVENT_ROW_WRITE
    ROW_RELEASE = EVENT_ROW_RELEASE
    LOADER_SLIM = EVENT_LOADER_SLIM
    COLUMN_WRITE = EVENT_COLUMN_WRITE
    RELATION_LOOKUP = EVENT_RELATION_LOOKUP
    STAGE_SPAN = EVENT_STAGE_SPAN
    OPERATOR_SPAN = EVENT_OPERATOR_SPAN
    ADAPTIVE_SCHEDULER_DECISION = EVENT_ADAPTIVE_SCHEDULER_DECISION
    OUTPUT_TARGET_END = EVENT_OUTPUT_TARGET_END

    # 策略 `signal`(默认不进入公共事件目录).
    PRE_USE_BATCH_SIZE = EVENT_PRE_USE_BATCH_SIZE

    WORKFLOW_STARTED = EVENT_WORKFLOW_STARTED
    WORKFLOW_FINISHED = EVENT_WORKFLOW_FINISHED

    WORKFLOW_NODE_START = EVENT_WORKFLOW_NODE_START
    WORKFLOW_NODE_END = EVENT_WORKFLOW_NODE_END
    WORKFLOW_NODE_CANCELLED = EVENT_WORKFLOW_NODE_CANCELLED

    WORKFLOW_CACHE_ACQUIRE = EVENT_WORKFLOW_CACHE_ACQUIRE
    WORKFLOW_CACHE_RELEASE = EVENT_WORKFLOW_CACHE_RELEASE
    WORKFLOW_CACHE_EVICT = EVENT_WORKFLOW_CACHE_EVICT

    WORKFLOW_RESOURCE_CREATE = EVENT_WORKFLOW_RESOURCE_CREATE
    WORKFLOW_RESOURCE_WRITE = EVENT_WORKFLOW_RESOURCE_WRITE
    WORKFLOW_RESOURCE_COMMIT = EVENT_WORKFLOW_RESOURCE_COMMIT
    WORKFLOW_RESOURCE_DISCARD = EVENT_WORKFLOW_RESOURCE_DISCARD

    @override
    def __str__(self) -> str:
        return str(self.value)


class WorkflowNodeEndStatus(str, Enum):
    """`workflow` 节点结束状态枚举(值保持不变)."""

    OK = WORKFLOW_NODE_END_STATUS_OK
    ERROR = WORKFLOW_NODE_END_STATUS_ERROR

    @override
    def __str__(self) -> str:
        return str(self.value)


class WorkflowNodeCancelledReason(str, Enum):
    """`workflow` 节点取消原因枚举(值保持不变)."""

    DEPENDENCY_FAILED = WORKFLOW_NODE_CANCELLED_REASON_DEPENDENCY_FAILED
    UPSTREAM_CANCELLED = WORKFLOW_NODE_CANCELLED_REASON_UPSTREAM_CANCELLED
    POLICY_ALL_FAIL = WORKFLOW_NODE_CANCELLED_REASON_POLICY_ALL_FAIL

    @override
    def __str__(self) -> str:
        return str(self.value)


__all__ = (
    "WORKFLOW_ATTRIBUTION_META_KEYS",
    "WORKFLOW_EXEC_ID_META_KEY",
    "WORKFLOW_NODE_ID_META_KEY",
    "Event",
    "EventDescriptor",
    "EventType",
    "WorkflowNodeCancelledReason",
    "WorkflowNodeEndStatus",
    "generate_run_id",
    "get_event_catalog",
    "get_event_catalog_map",
    "now_ts",
)
