schema: spec-driven
<<<<<<<< HEAD:openspec/notplan-changes/c15-workflow-intermediate-store-optimizations/.openspec.yaml
created: 2026-03-24
========
created: 2026-03-25
>>>>>>>> 7882a67 (Squash commits from issue-run-override-outputs):openspec/changes/c21-yaml-dsl-output-overrides-v2/.openspec.yaml
