# ruff: noqa: T201
from __future__ import annotations

import argparse
import difflib
import runpy
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Dict, Iterable, List, Tuple

project_meta = SimpleNamespace(**runpy.run_path(str(Path(__file__).with_name("project-meta.py"))))


def _require_str(value: Any, key: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError("期望 {} 为非空字符串(实际为 {!r})".format(key, value))
    return value


def _load_identity(pyproject: Dict[str, Any]) -> Dict[str, str]:
    project = pyproject.get("project") or {}
    tool = pyproject.get("tool") or {}
    scalim = (tool.get("scalim") or {}) if isinstance(tool, dict) else {}

    dist_name = _require_str(project.get("name"), "project.name")
    version = _require_str(project.get("version"), "project.version")

    identity = scalim.get("identity") or {}
    viz = scalim.get("viz") or {}
    env = scalim.get("env") or {}

    import_root = _require_str(identity.get("import_root"), "tool.scalim.identity.import_root")
    cli_name = _require_str(identity.get("cli_name"), "tool.scalim.identity.cli_name")

    viz_dir_name = _require_str(viz.get("dir_name"), "tool.scalim.viz.dir_name")
    viz_artifacts_root = _require_str(viz.get("artifacts_root"), "tool.scalim.viz.artifacts_root")
    viz_replay_route = _require_str(viz.get("replay_route"), "tool.scalim.viz.replay_route")

    bench_env = env.get("bench") or {}
    sync_env = env.get("sync") or {}
    probes_env = env.get("probes") or {}
    bench_scale = _require_str(bench_env.get("scale"), "tool.scalim.env.bench.scale")
    bench_scope = _require_str(bench_env.get("scope"), "tool.scalim.env.bench.scope")
    bench_max_workers = _require_str(bench_env.get("max_workers"), "tool.scalim.env.bench.max_workers")

    sync_remote_host = _require_str(sync_env.get("remote_host"), "tool.scalim.env.sync.remote_host")
    sync_tmp_remote_dir = _require_str(sync_env.get("tmp_remote_dir"), "tool.scalim.env.sync.tmp_remote_dir")
    sync_log_remote_dir = _require_str(sync_env.get("log_remote_dir"), "tool.scalim.env.sync.log_remote_dir")
    sync_log_dest_dir = _require_str(sync_env.get("log_dest_dir"), "tool.scalim.env.sync.log_dest_dir")
    sync_dest_dir = _require_str(sync_env.get("dest_dir"), "tool.scalim.env.sync.dest_dir")
    sync_report_root_dir = _require_str(sync_env.get("report_root_dir"), "tool.scalim.env.sync.report_root_dir")
    sync_analysis_script = _require_str(sync_env.get("analysis_script"), "tool.scalim.env.sync.analysis_script")
    sync_analyze_args = _require_str(sync_env.get("analyze_args"), "tool.scalim.env.sync.analyze_args")
    sync_analyze_args_prefix = _require_str(sync_env.get("analyze_args_prefix"), "tool.scalim.env.sync.analyze_args_prefix")

    probe_call_by_dep_cardinality = _require_str(
        probes_env.get("call_by_dep_cardinality"),
        "tool.scalim.env.probes.call_by_dep_cardinality",
    )

    return {
        "DIST_NAME": dist_name,
        "VERSION": version,
        "IMPORT_ROOT": import_root,
        "CLI_NAME": cli_name,
        "VIZ_DIR_NAME": viz_dir_name,
        "VIZ_ARTIFACTS_ROOT": viz_artifacts_root,
        "VIZ_REPLAY_ROUTE": viz_replay_route,
        "ENV_BENCH_SCALE": bench_scale,
        "ENV_BENCH_SCOPE": bench_scope,
        "ENV_BENCH_MAX_WORKERS": bench_max_workers,
        "ENV_SYNC_REMOTE_HOST": sync_remote_host,
        "ENV_SYNC_TMP_REMOTE_DIR": sync_tmp_remote_dir,
        "ENV_SYNC_LOG_REMOTE_DIR": sync_log_remote_dir,
        "ENV_SYNC_LOG_DEST_DIR": sync_log_dest_dir,
        "ENV_SYNC_DEST_DIR": sync_dest_dir,
        "ENV_SYNC_REPORT_ROOT_DIR": sync_report_root_dir,
        "ENV_SYNC_ANALYSIS_SCRIPT": sync_analysis_script,
        "ENV_SYNC_ANALYZE_ARGS": sync_analyze_args,
        "ENV_SYNC_ANALYZE_ARGS_PREFIX": sync_analyze_args_prefix,
        "ENV_PROBE_CALL_BY_DEP_CARDINALITY": probe_call_by_dep_cardinality,
    }


def _python_constants_text(values: Dict[str, str]) -> str:
    keys = sorted(values.keys())
    lines: List[str] = [
        "# 本文件由 `scripts/gen-project-constants.py` 自动生成,请勿手改.",
        "# 数据来源: `pyproject.toml` 的 `([project] + [tool.scalim.*])`.",
        "",
    ]
    for key in keys:
        lines.append('{} = "{}"'.format(key, values[key].replace('"', '\\"')))
    lines.append("")
    lines.append("__all__ = ()")
    lines.append("")
    return "\n".join(lines)


def _ts_constants_text(values: Dict[str, str]) -> str:
    keys = sorted(values.keys())
    lines: List[str] = [
        "// Generated by scripts/gen-project-constants.py. Do not edit by hand.",
        "",
    ]
    for key in keys:
        lines.append('export const {} = "{}";'.format(key, values[key].replace('"', '\\"')))
    lines.append("")
    return "\n".join(lines)


def _write_if_changed(path: Path, content: str) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    if existing == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _diff(a: str, b: str, a_name: str, b_name: str) -> str:
    return "\n".join(
        difflib.unified_diff(
            a.splitlines(),
            b.splitlines(),
            fromfile=a_name,
            tofile=b_name,
            lineterm="",
        )
    )


def _check_exact(path: Path, expected: str) -> Tuple[bool, str]:
    got = path.read_text(encoding="utf-8") if path.exists() else ""
    if got == expected:
        return True, ""
    d = _diff(got, expected, str(path), str(path) + " (expected)")
    return False, d


def _targets(root: Path, values: Dict[str, str]) -> List[Tuple[Path, str]]:
    import_root = values["IMPORT_ROOT"]
    python_path = root / "src" / import_root / "_project_constants.py"
    viz_ts_path = root / "frontend" / "scalim-viz" / "src" / "generated" / "project_constants.ts"

    python_text = _python_constants_text(values)
    ts_text = _ts_constants_text(values)
    return [
        (python_path, python_text),
        (viz_ts_path, ts_text),
    ]


def main(argv: Iterable[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="从 `pyproject.toml` 生成项目常量(Python + TS).")
    p.add_argument("--check", action="store_true", help="仅检查漂移,不写入文件.")
    args = p.parse_args(list(argv or sys.argv[1:]))

    root = project_meta.repo_root()
    pyproject = project_meta.load_pyproject(root)
    values = _load_identity(pyproject)

    changed: List[Path] = []
    failed: List[Tuple[Path, str]] = []

    for path, expected in _targets(root, values):
        if args.check:
            ok, diff = _check_exact(path, expected)
            if not ok:
                failed.append((path, diff))
        else:
            if _write_if_changed(path, expected):
                changed.append(path)

    if args.check:
        if failed:
            sys.stderr.write("检测到项目常量漂移:\n")
            for path, diff in failed:
                sys.stderr.write("\n--- {}\n{}\n".format(str(path), diff or "(无法获取 diff)"))
            sys.stderr.write("\n修复: 运行 `just gen-project-constants`\n")
            return 1
        sys.stdout.write("OK: 项目常量与 `pyproject.toml` 一致\n")
        return 0

    if changed:
        sys.stdout.write("已更新:\n")
        for path in changed:
            sys.stdout.write("  - {}\n".format(str(path)))
    else:
        sys.stdout.write("无变更.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
