#!/usr/bin/env python3
"""生成一个 `.tmp/` 内的“公共接口跳转辅助导入文件”.

目的:
- 方便在编辑器/语言服务器中快速跳转到公共接口符号定义(无需在项目里手写大量 `import`)。
- 生成物也可直接执行,用于对 Tier 1 public API 做 import smoke（`python .tmp/public_api_jump_imports.py`）。
- 生成物放在 `.tmp/`，不提交，也不影响 `basedpyright` 门禁。

单一事实来源:
- 入口列表通过 `src/scalim/**/__init__.py` 中的注释标注发现:
  `# pragma: scalim-public-api tier1:<order>:<module>|<desc>|<scenario>`
- 每个模块的导出符号集合来自该模块的 `__all__` 字面量(`tuple`/`list`)。
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

from public_api_tooling import (
    PublicApiEntrypointMarker,
    PublicApiProblem,
    discover_public_api_entrypoints,
    extract_literal_module_all,
    repo_root_for_script,
    resolve_module_source_path,
)


def _as_ident(value: str) -> str:
    # 模块名 -> 合法的 `Python` 标识符
    return re.sub(r"[^A-Za-z0-9_]", "_", str(value))


def _render_jump_file(
    entrypoints: Sequence[PublicApiEntrypointMarker],
    *,
    exports_by_module: Dict[str, Tuple[str, ...]],
    generated_by: str,
) -> str:
    lines: List[str] = [
        "# pyright: ignore",
        "# This file is generated. Do not edit or commit.",
        "#",
        "# Generated by: {}".format(generated_by),
        "# Purpose: editor/LSP jump-to-definition helpers for Tier 1 public API.",
        "#",
        "# Usage:",
        "#   - Editor: open this file and jump from the imports below.",
        "#   - Smoke test: `python .tmp/public_api_jump_imports.py` (imports Tier 1 public API exports).",
        "#",
        "from typing import TYPE_CHECKING",
        "",
    ]

    jump_func_names: List[str] = []

    for entry in entrypoints:
        exports = exports_by_module.get(entry.module, ())

        func_name = "_jump_{}".format(_as_ident(entry.module))
        jump_func_names.append(func_name)
        lines.append("def {}() -> None:".format(func_name))
        lines.append('    """{} | {}"""'.format(entry.description, entry.common_scenario))

        names = [n for n in exports if str(n).isidentifier()]
        if not names:
            lines.append("    return")
            lines.append("")
            continue

        lines.append("    from {} import (".format(entry.module))
        for name in names:
            lines.append("        {},".format(name))
        lines.append("    )")
        lines.append("")

    lines.append("def run_all() -> None:")
    if not jump_func_names:
        lines.append("    return")
    else:
        for func_name in jump_func_names:
            lines.append("    {}()".format(func_name))
    lines.append("")
    lines.append("if TYPE_CHECKING:")
    lines.append("    run_all()")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    run_all()")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _as_relpath(path: Path, *, repo_root: Path) -> str:
    return str(path.relative_to(repo_root)).replace("\\", "/")


def _format_problems(problems: Sequence[PublicApiProblem], *, repo_root: Path) -> str:
    lines: List[str] = []
    for p in problems:
        rel = _as_relpath(p.path, repo_root=repo_root) if p.path.exists() else str(p.path)
        module = str(p.module or "(unknown)")
        lines.append("- {}:{}: {}: {}".format(rel, int(p.lineno), module, p.reason))
    return "\n".join(lines)


def _collect_entrypoint_exports(
    entrypoints: Sequence[PublicApiEntrypointMarker], *, repo_root: Path
) -> Tuple[Dict[str, Tuple[str, ...]], Tuple[PublicApiProblem, ...]]:
    problems: List[PublicApiProblem] = []
    exports_by_module: Dict[str, Tuple[str, ...]] = {}

    for entry in entrypoints:
        module_path = resolve_module_source_path(repo_root, entry.module)
        if module_path is None:
            problems.append(
                PublicApiProblem(
                    path=entry.marker_path,
                    lineno=entry.marker_lineno,
                    module=entry.module,
                    reason="在 `src/` 下找不到入口模块（期望存在 `src/{}.py` 或 `src/{}/__init__.py`）".format(
                        entry.module.replace(".", "/"),
                        entry.module.replace(".", "/"),
                    ),
                )
            )
            continue

        all_literal, err = extract_literal_module_all(module_path, repo_root=repo_root)
        if all_literal is None:
            problems.append(
                PublicApiProblem(
                    path=entry.marker_path,
                    lineno=entry.marker_lineno,
                    module=entry.module,
                    reason="入口模块必须声明字面量 `__all__`（模块文件: {}）：{}".format(
                        _as_relpath(module_path, repo_root=repo_root),
                        str(err or "unknown error"),
                    ),
                )
            )
            continue

        exports_by_module[str(entry.module)] = all_literal.values

    return exports_by_module, tuple(sorted(problems, key=lambda p: (str(p.path), int(p.lineno), str(p.module), str(p.reason))))


def main(argv: Sequence[str] | None = None) -> int:
    _ = argv
    repo_root = repo_root_for_script(Path(__file__))
    entrypoints, marker_problems = discover_public_api_entrypoints(repo_root, tier=1)
    exports_by_module, export_problems = _collect_entrypoint_exports(entrypoints, repo_root=repo_root)
    problems = tuple(marker_problems) + tuple(export_problems)
    if problems:
        sys.stderr.write("[错误] 公共接口跳转辅助文件生成失败 ({} 个问题):\n".format(len(problems)))
        sys.stderr.write(_format_problems(problems, repo_root=repo_root))
        sys.stderr.write("\n")
        return 1

    out_dir = repo_root / ".tmp"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "public_api_jump_imports.py"
    out_path.write_text(
        _render_jump_file(
            entrypoints,
            exports_by_module=exports_by_module,
            generated_by="python scripts/gen-public-api-jump-imports.py",
        ),
        encoding="utf-8",
    )
    print("已写入", str(out_path.relative_to(repo_root)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
